### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by KyleLine** [deepcam-cn/yolov5-face#147]
在detect_face.py中导入权重yolov5s.pt，运行后报错：

Traceback (most recent call last):
  File "/home/lcy/YOLO/yolov5-face-master/detect_face.py", line 148, in <module>
    detect_one(model, opt.image, device)
  File "/home/lcy/YOLO/yolov5-face-master/detect_face.py", line 88, in detect_one
    imgsz = check_img_size(img_size, s=model.stride.max())  # check img_size
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

**Comment by derronqi** [comment]
pytorch version <= 1.8

**Comment by JustVinh** [comment]
> pytorch version <= 1.8

Didn't work sir
