### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, '\xff'.

### ISSUE THREAD

**Issue by jinfei3459** [deepcam-cn/yolov5-face#165]
when i use pretrain model to run detect_face.py, the following error occurred
```
(py37) root@0c10d27be41d:/home/zalend/data/zjf/docker/project/yolov5-face# python detect_face.py --weights weights/yolov5s-face.pt data/images/test.jpg
Namespace(image='data/images/test.jpg', img_size=640, weights=['weights/yolov5s-face.pt', 'data/images/test.jpg'])
device =  cuda
device =  cuda:0
attempt_download file =  weights/yolov5s-face.pt
Fusing layers...
/root/miniconda3/envs/py37/lib/python3.7/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
attempt_download file =  data/images/test.jpg
Traceback (most recent call last):
  File "detect_face.py", line 150, in <module>
    model = load_model(opt.weights, device)
  File "detect_face.py", line 21, in load_model
    model = attempt_load(weights, map_location=device)  # load FP32 model
  File "/home/zalend/data/zjf/docker/project/yolov5-face/models/experimental.py", line 118, in attempt_load
    model.append(torch.load(w, map_location=map_location)['model'].float().fuse().eval())  # load FP32 model
  File "/root/miniconda3/envs/py37/lib/python3.7/site-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/root/miniconda3/envs/py37/lib/python3.7/site-packages/torch/serialization.py", line 777, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\xff'.
```

**Comment by jinfei3459** [comment]
> when i use pretrain model to run detect_face.py, the following error occurred
> 
> ```
> (py37) root@0c10d27be41d:/home/zalend/data/zjf/docker/project/yolov5-face# python detect_face.py --weights weights/yolov5s-face.pt data/images/test.jpg
> Namespace(image='data/images/test.jpg', img_size=640, weights=['weights/yolov5s-face.pt', 'data/images/test.jpg'])
> device =  cuda
> device =  cuda:0
> attempt_download file =  weights/yolov5s-face.pt
> Fusing layers...
> /root/miniconda3/envs/py37/lib/python3.7/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
>   return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
> attempt_download file =  data/images/test.jpg
> Traceback (most recent call last):
>   File "detect_face.py", line 150, in <module>
>     model = load_model(opt.weights, device)
>   File "detect_face.py", line 21, in load_model
>     model = attempt_load(weights, map_location=device)  # load FP32 model
>   File "/home/zalend/data/zjf/docker/project/yolov5-face/models/experimental.py", line 118, in attempt_load
>     model.append(torch.load(w, map_location=map_location)['model'].float().fuse().eval())  # load FP32 model
>   File "/root/miniconda3/envs/py37/lib/python3.7/site-packages/torch/serialization.py", line 608, in load
>     return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
>   File "/root/miniconda3/envs/py37/lib/python3.7/site-packages/torch/serialization.py", line 777, in _legacy_load
>     magic_number = pickle_module.load(f, **pickle_load_args)
> _pickle.UnpicklingError: invalid load key, '\xff'.
> ```

my torch version 1.10.0+cu111

**Comment by jinfei3459** [comment]
Wrong parameter
