### ISSUE TITLE
when I train widerface,error occured

### ISSUE THREAD

**Issue by futureflsl** [deepcam-cn/yolov5-face#18]
Traceback (most recent call last):
  File "train.py", line 513, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "train.py", line 299, in train
    scaler.step(optimizer)  # optimizer.step
  File "/home/fut/miniconda3/lib/python3.8/site-packages/torch/cuda/amp/grad_scaler.py", line 321, in step
    retval = optimizer.step(*args, **kwargs)
  File "/home/fut/miniconda3/lib/python3.8/site-packages/torch/optim/lr_scheduler.py", line 67, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/fut/miniconda3/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/home/fut/miniconda3/lib/python3.8/site-packages/torch/optim/sgd.py", line 106, in step
    buf.mul_(momentum).add_(d_p, alpha=1 - dampening)
RuntimeError: The size of tensor a (32) must match the size of tensor b (24) at non-singleton dimension 0

**Comment by Bohrhh** [comment]
+1

**Comment by yongjingli** [comment]
@derronqi same question

**Comment by ssmy199** [comment]
+1

**Comment by ssmy199** [comment]
Change yolov5s-face.pt to yolov5 official file>>yolov5s.pt，this is my solution
