### ISSUE TITLE
RuntimeError: Sizes of tensors must match except in dimension 0. Got 0 and 222 (The offending index is 2)

### ISSUE THREAD

**Issue by Z-Xiong** [deepcam-cn/yolov5-face#30]
Run detect_face.py

```
Namespace(image='data/images/test.jpg', img_size=640, weights='yolov5s.pt')
Fusing layers... 
Traceback (most recent call last):
  File "yolov5-face/detect_face.py", line 148, in <module>
    detect_one(model, opt.image, device)
  File "yolov5-face/detect_face.py", line 108, in detect_one
    pred = non_max_suppression_face(pred, conf_thres, iou_thres)
  File "yolov5-face/utils/general.py", line 424, in non_max_suppression_face
    x = torch.cat((box[i], x[i, j + 15, None], x[:, 5:15] ,j[:, None].float()), 1)
RuntimeError: Sizes of tensors must match except in dimension 0. Got 0 and 222 (The offending index is 2)

Process finished with exit code 1
```

How to sovle it?

**Comment by s-trooper** [comment]
Hi, i have the same error. How do you solved it?

**Comment by Amrsaeed** [comment]
Same issue here
