### ISSUE TITLE
not able to convert from .pt to .wts

### ISSUE THREAD

**Issue by rahulsharma11** [deepcam-cn/yolov5-face#98]
Hi,
i tried to convert yolov5s-face.pt to yolov5s-face.wts from - "https://github.com/wang-xinyu/tensorrtx/tree/master/yolov5".
python3 gen_wts.py -w yolov5s-face.pt

Getting error-
YOLOv5 🚀 v6.0-109-g7c6bae0 torch 1.10.0+cu102 CPU

Traceback (most recent call last):
  File "gen_wts.py", line 30, in <module>
    model = torch.load(pt_file, map_location=device)['model'].float()  # load to FP32
  File "/home/inkers/.local/lib/python3.8/site-packages/torch/serialization.py", line 607, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/inkers/.local/lib/python3.8/site-packages/torch/serialization.py", line 882, in _load
    result = unpickler.load()
  File "/home/inkers/.local/lib/python3.8/site-packages/torch/serialization.py", line 875, in find_class
    return super().find_class(mod_name, name)
AttributeError: Can't get attribute 'StemBlock' on <module 'models.common' from '/home/inkers/rahul/yolov5_tensorrtx/yolov5/models/common.py'>

Any suggestion?
Thanks.

One more question-
Can i use this model and use yolov5 parser for this model?
Thanks in advance.

**Comment by rahulsharma11** [comment]
hi,
its done.

**Comment by ch4ki** [comment]
> hi, its done.

Hi, how did u solve the problem
